### ISSUE TITLE
Instance/ModuleHost: Instance "generic-midi" failed to init: Error: Failed to initialise RtMidi Error: Failed to initialise RtMidi

### ISSUE THREAD

**Issue by tehsu** [bitfocus/companion-module-generic-midi#3]
Is there anything that is needed for RtMidi?

**Comment by MeestorX** [comment]
I believe that's an error that you can see when there are no MIDI ports. It's an issue with the RtMidi library, not the companion generic-midi module per se.
If you want to send me the support bundle (if possible, via my site: discourse.checkcheckonetwo.com) I can report this to the RtMIDI people.

**Comment by tehsu** [comment]
Ahh that would make sense as the MIDI isn't running on this computer
