### ISSUE TITLE
[BUG] Triggers on MIDI Notes only run once

### ISSUE THREAD

**Issue by jedwards747** [bitfocus/companion-module-generic-midi#6]
I have a list of triggers set up to fire on MIDI Note On events. When I first start Companion or enable the MIDI connection, and run through each note to test the triggers, everything fires as intended. However, each trigger only fires once--if I send any of the MIDI notes again, the trigger never fires again. It's like the triggers are "one-time-only" events, but I would like them to fire every time the corresponding MIDI note is received.

Reproduce:
1. Set up a generic-midi connection module.
2. Set up triggers with the Event: When Condition is true and with the Condition: generic-midi: Receive MIDI Message, Event: Note On, with the note # being set to various note numbers.
3. Send the MIDI notes one at a time for each trigger.
4. The triggers will fire.
5. Send the MIDI notes one at a time for each trigger, again.
6. The triggers will not fire.

Expected behavior:
The triggers will fire each time the MIDI Note On is received for that condition, regardless of if it has already run before.

Environment:
- OS: Windows 10 Pro (10.0.19045 Build 19045)
- Browser: Firefox 129.0.1
- Companion Version: 3.3.1+7001-stable-ee7c3daa

I am very new to Companion so this could just be a misconfiguration.

**Comment by MeestorX** [comment]
I have a video on my support site on how to trigger an action from a MIDI message.
https://discourse.checkcheckonetwo.com/t/companion-generic-midi-module/3890/25
