### ISSUE TITLE
Use variable for noteOn/noteOff

### ISSUE THREAD

**Issue by slaygon** [bitfocus/companion-module-generic-midi#7]
As I am experimenting a bit with a panel where I have multiple functions targeting decks in Traktor, I update an internal variable that indicates which deck I want to target, I would want to be able to use variables in the "Note Number" field, rather than just the Velocity field.

For now, I am using a python script I trigger with a shell command action from Companion like so: bash -c "cd /streamdeck/scripts && python3 midi.py 2 $((83+$(internal:custom_deck_select)))" where the "custom_deck_select" is the deck I want to target. 84 (83+custom_dec_select) targets Deck A in Traktor with a Rewind command, 85 Deck B and so forth.

I then have mapped 79+custom_deck_select similarly, but mapped those to the Play command in Traktor.

However, since you can't use variables for the Note Number, this flexibility does not exist currently.

**Comment by MeestorX** [comment]
Would this update work? https://discourse.checkcheckonetwo.com/t/request-variables-for-generic-midi
I plan to make this change when I get a chance.

**Comment by slaygon** [comment]
I guess it would, as long as it is implemented with the original posters question in mind: "And would it be possible to get a ‘generic’ send MIDI action, that has variable enabled fields for type, channel, number, value?"

**Comment by MeestorX** [comment]
Oh, you're speaking of sending. Gotcha. So, when clicking "use variables", it could allow the note number in addition to the velocity to be set by a variable is what you're looking for?

**Comment by slaygon** [comment]
Yes, exactly. Currently you can only use a variable for the velocity, but not the note, which is what I am looking for.

**Comment by MeestorX** [comment]
I just uploaded v1.2.2 which should have the ability to use variables for all parameters now.
Please give it a try and let me know how it works.
https://discourse.checkcheckonetwo.com/t/companion-v3-x-x-modules-for-yamaha-and-the-new-generic-midi-module/3456/3

**Comment by MeestorX** [comment]
v1.2.2 had some problems. Please try the latest (v1.3.0) which from other reports seems to be working. LMK if you find any issues.

**Comment by slaygon** [comment]
> v1.2.2 had some problems. Please try the latest (v1.3.0) which from other reports seems to be working. LMK if you find any issues.

Thank you kindly. Will do some testing soon!
